dist: trusty
sudo: required

services: 

language: 

before_install:

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  - docker build -t $DOCKER_USER/prueba.travis:latest .
  - docker push $DOCKER_USER/prueba.travis:latest
